// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien.Data;

#nullable disable

namespace QuanLyThuVien.Migrations
{
    [DbContext(typeof(QLTVContext))]
    [Migration("20260323170032_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThuVien.Data.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhieuMuonID")
                        .HasColumnType("int");

                    b.Property<int>("SachID")
                        .HasColumnType("int");

                    b.Property<int>("SoLanGiaHan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhieuMuonID");

                    b.HasIndex("SachID");

                    b.ToTable("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.GoiThanhVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLanGiaHanToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayMuonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoSachDuocMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoThangHieuLuc")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("GoiThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.NhaXuatBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("ThanhVienID")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("ThanhVienID");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuThu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LoaiThu")
                        .HasColumnType("int");

                    b.Property<string>("LyDoThu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThanhVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("ThanhVienID");

                    b.ToTable("PhieuThu");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("NhaXuatBanID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TacGiaID")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TheLoaiID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhaXuatBanID");

                    b.HasIndex("TacGiaID");

                    b.HasIndex("TheLoaiID");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TacGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoiThanhVienID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanViPham")
                        .HasColumnType("int");

                    b.Property<string>("TenThanhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GoiThanhVienID");

                    b.ToTable("ThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TheLoai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuon")
                        .HasForeignKey("PhieuMuonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.Sach", "Sach")
                        .WithMany("ChiTietPhieuMuon")
                        .HasForeignKey("SachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuMuon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.ThanhVien", "ThanhVien")
                        .WithMany("PhieuMuon")
                        .HasForeignKey("ThanhVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuThu", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuThu")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.ThanhVien", "ThanhVien")
                        .WithMany("PhieuThu")
                        .HasForeignKey("ThanhVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Sach")
                        .HasForeignKey("NhaXuatBanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.TacGia", "TacGia")
                        .WithMany("Sach")
                        .HasForeignKey("TacGiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.TheLoai", "TheLoai")
                        .WithMany("Sach")
                        .HasForeignKey("TheLoaiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TacGia");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.GoiThanhVien", "GoiThanhVien")
                        .WithMany("ThanhVien")
                        .HasForeignKey("GoiThanhVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.GoiThanhVien", b =>
                {
                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.NhaXuatBan", b =>
                {
                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.NhanVien", b =>
                {
                    b.Navigation("PhieuMuon");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.Navigation("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TacGia", b =>
                {
                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.Navigation("PhieuMuon");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TheLoai", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
