// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien.Data;

#nullable disable

namespace QuanLyThuVien.Migrations
{
    [DbContext(typeof(QLTVContext))]
    [Migration("20260315071725_CapNhatCode")]
    partial class CapNhatCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThuVien.Data.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhieuMuonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaSach");

                    b.HasIndex("PhieuMuonID");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.GoiThanhVien", b =>
                {
                    b.Property<string>("MaGoi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoSachDuocMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoThangHieuLuc")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGoi");

                    b.ToTable("GoiThanhViens");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuThu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LyDoThu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("PhieuThus");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.Property<string>("MaThanhVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThanhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThanhVien");

                    b.HasIndex("MaGoi");

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TheLoai", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.Sach", "Sach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien.Data.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("PhieuMuonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.ThanhVien", "ThanhVen")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVen");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuThu", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.ThanhVien", "ThanhVien")
                        .WithMany("PhieuThus")
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.TheLoai", "TheLoai")
                        .WithMany("Sachs")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.HasOne("QuanLyThuVien.Data.GoiThanhVien", "GoiThanhVien")
                        .WithMany("ThanhViens")
                        .HasForeignKey("MaGoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiThanhVien");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.GoiThanhVien", b =>
                {
                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.Sach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.ThanhVien", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuThus");
                });

            modelBuilder.Entity("QuanLyThuVien.Data.TheLoai", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
